### ISSUE TITLE
Just a general question

### ISSUE THREAD

**Issue by francoisw** [joeguilmette/wp-local-toolbox#14]
Hi there,

Just a general question regarding the toolbox -- will the plugin also manage the settings for the different environments as in the wp-config file eg. database name, database host etc to tell WordPress which database etc. it should use or do you need to set this manually? 

Thanks
Francois Wessels

**Comment by jb510** [comment]
No.  There is no GUI to control settings (other than the toggle for Airplane mode).  That's all set manually as normal.
