### ISSUE TITLE
Add functionality to display page template in admin bar

### ISSUE THREAD

**Issue by joeguilmette** [joeguilmette/wp-local-toolbox#2]

**Comment by joeguilmette** [comment]
https://wordpress.org/plugins/show-current-template/

**Comment by jb510** [comment]
Currently I use Query Monitor which includes this https://wordpress.org/plugins/query-monitor/

**Comment by jb510** [comment]
Fwiw, I used to use the debug bar extension https://github.com/Clorith/wordpress-debug-bar-template-trace

John/9seeds helped write this ages ago https://wordpress.org/plugins/what-template-file-am-i-viewing/I

And I prefered this me before QueryMonitor came along https://wordpress.org/plugins/what-the-file/

Now I _always_use query monitor, so for me there would be a reason to duplicate that functionality.

**Comment by joeguilmette** [comment]
> Now I _always_use query monitor, so for me there would be a reason to duplicate that functionality.

Would or would not?

Query monitor looks great. Although one thing I notice is that it displays the page template, but not the includes being called by that template.

**Comment by jb510** [comment]
Sorry.   iPad.  Would a NOT be a reason to duplicate.

**Comment by joeguilmette** [comment]
You're right - there are many plugins to do this, and it'd be better to just use one and deactivate with WPLT in production if necessary.
