### ISSUE TITLE
Are there any plans to fully update this plugin?

### ISSUE THREAD

**Issue by mrapino** [joeguilmette/wp-local-toolbox#27]
Hello, 

I was wondering if there were any plans to revamp this plugin? Is it completely out of date, or is it still safe to use and fully tested?

Thanks!

**Comment by jb510** [comment]
Revamp how/why?  I use this plugin on all sites every day...

**Comment by mrapino** [comment]
The reason I ask is because I found you guys through the WP Repo, and the info on that page says Compatible up to: 4.2.10, Last Updated: 2 years ago. I wanted to reach out to see if this plugin was still being actively developed, because as WordPress standards change, issues with older plugin code could become an issue. 

Thanks for your reply!

**Comment by jb510** [comment]
This plugin is a framework for you to customize to suit your personal local development needs.  It does everything I (and I assume Joe) really wants it to do for now so I wouldn't expect any updates. 

Pull requests are welcome though.  

 The version in the repo was an experiment (Joe's) in distributing it as a standard plugin, but it's always really been intended to function at an mu-plugin and the repo doesn't really provide for that sort of thing.  We talked about building a feature self-install a helper as an mu plugin, but frankly that's a lot of work that seems unnecessary given the intended use/demographic. There's nothing "user" about this plugin.

**Comment by mrapino** [comment]
Thanks, I appreciate the info.
