### ISSUE TITLE
Force admin bar on local

### ISSUE THREAD

**Issue by jb510** [joeguilmette/wp-local-toolbox#6]
I shared this with some friends at the Orange County WordPress Meetup, they loved it!

Tabby mentioned that on her client sites client's often disable the admin bar and it's be great to include a way to force the admin bar back on when WPLT_SERVER is set.

**Comment by joeguilmette** [comment]
This is a great idea. I wanted to add another flag for wp-config that would allow you to force enabling or disabling the admin bar.

**Comment by jb510** [comment]
tagging @tabbymarie

**Comment by tabbymarie** [comment]
Perfect I think it should def be a flag that we can set but having the bar on on dev sites is a great and helpful indicator. I love this plugin! Downloading it today!

**Comment by joeguilmette** [comment]
Added: 

**WPLT_ADMINBAR**: Show or hide the admin bar on the frontend. `FALSE` will force it to be hidden, `TRUE` will force it to display, `ALWAYS` will display the admin bar even when logged out. These settings will override the 'Show toolbar' setting in the Users > Your Profile and `add_filter('show_admin_bar', '__return_false');` in functions.php, but doesn't attempt to overcome any CSS based hiding of the admin bar.
